# @format

name: Build and Deploy LaTeX CV

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Compile LaTeX to PDF
        uses: xu-cheng/latex-action@v2
        with:
          root_file: cv.tex

      - name: Use Docker to Convert PDF to HTML
        run: |
          docker run --rm -v ${{ github.workspace }}:/data bwits/pdf2htmlex pdf2htmlEX /data/cv.pdf /data/cv.html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
          publish_branch: gh-pages
          keep_files: true
