# @format

name: Build and Deploy LaTeX CV

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Compile LaTeX to PDF
        uses: xu-cheng/latex-action@v2
        with:
          root_file: cv.tex

      - name: Install pdf2htmlEX
        run: |
          sudo apt-get update
          sudo apt-get install -y pdf2htmlEX

      - name: Convert PDF to HTML
        run: pdf2htmlEX cv.pdf cv.html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
          publish_branch: gh-pages
          keep_files: true
          force_orphan: true
